apiVersion: apps/v1
kind: Deployment
metadata:
  name: statusview
  labels:
    app: statusview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statusview
  template:
    metadata:
      labels:
        app: statusview
    spec:
      containers:
        - name: statusview
          image: username/statusview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5